import type { ICustomer } from ".";

export const customers: ICustomer[] = [
  {
    id: 1,
    name: "Andi Saputra",
    email: "andi@mail.com",
    plan: "Gold Protection",
    currentPremi: "Rp4.000.000",
    totalPremi: "Rp18.500.000",
    progress: 33,
    duration: "4/12",
    status: "ACTIVE",
    avatar: "https://i.pravatar.cc/150?img=1",
  },
  {
    id: 2,
    name: "Budi Santoso",
    email: "budi@mail.com",
    plan: "Silver Life",
    currentPremi: "Rp7.000.000",
    totalPremi: "Rp25.000.000",
    progress: 58,
    duration: "7/12",
    status: "ACTIVE",
    avatar: "https://i.pravatar.cc/150?img=2",
  },
  {
    id: 3,
    name: "Citra Lestari",
    email: "citra@mail.com",
    plan: "Family Secure",
    currentPremi: "Rp12.000.000",
    totalPremi: "Rp40.000.000",
    progress: 100,
    duration: "12/12",
    status: "INACTIVE",
    avatar: "https://i.pravatar.cc/150?img=3",
  },
  {
    id: 4,
    name: "Dimas Pratama",
    email: "dimas@mail.com",
    plan: "Smart Invest",
    currentPremi: "Rp2.000.000",
    totalPremi: "Rp15.000.000",
    progress: 17,
    duration: "2/12",
    status: "ACTIVE",
    avatar: "https://i.pravatar.cc/150?img=4",
  },
  {
    id: 5,
    name: "Eka Putri",
    email: "eka@mail.com",
    plan: "Prime Health",
    currentPremi: "Rp9.000.000",
    totalPremi: "Rp32.000.000",
    progress: 75,
    duration: "9/12",
    status: "ACTIVE",
    avatar: "https://i.pravatar.cc/150?img=5",
  },
  {
    id: 6,
    name: "Farhan Hidayat",
    email: "farhan@mail.com",
    plan: "Ultimate Guard",
    currentPremi: "Rp6.000.000",
    totalPremi: "Rp21.000.000",
    progress: 50,
    duration: "6/12",
    status: "ACTIVE",
    avatar: "https://i.pravatar.cc/150?img=6",
  },
  {
    id: 7,
    name: "Gina Maharani",
    email: "gina@mail.com",
    plan: "Executive Plan",
    currentPremi: "Rp12.000.000",
    totalPremi: "Rp50.000.000",
    progress: 100,
    duration: "12/12",
    status: "INACTIVE",
    avatar: "https://i.pravatar.cc/150?img=7",
  },
];
